### ISSUE TITLE
Request - Addition of other Anime4k models

### ISSUE THREAD

**Issue by AllrDan** [kato-megumi/anime4kOnnx#1]
Thank you so much for making this!! I was looking everywhere for Anime4k models compatible with chaiNNer.

Would it be possible for you to add the remaining models [found here](https://github.com/bloc97/Anime4K/tree/master/glsl), especially the ones in the _Deblur_ and _Experimental-Effects_ folders?

Much appreciated!

**Comment by kato-megumi** [comment]
Glad it helped!
The Sharder in Deblur and Experimental-Effects isn't from CNN like others, so I have no idea how, or if it's even possible, to port it to ONNX.

**Comment by AllrDan** [comment]
That makes sense, those models aren't upscaling ones like the others.
Thanks for the info!
